name: Java CI with Gradle

on:
  pull_request:
    branches:
      - develop
      - feature/issue-4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
